@startuml Casa
class TipoAcabamento {

}
class TipoTelha {

}
class TipoVidro {

}


class Parede { 
    altura: number
    largura: number
    Acabamento: TipoAcabamento
}

class Telhado {
    area: number
    Acabamento: TipoTelha
}

class Espelho {
    tipoVidro: TipoVidro
    altura: number
    largura: number
}

class Moradia {
    area: number
}

class Casa extends Moradia {
    telhadoAreaExterna: Telhado
    telhadoAreaInterna: Telhado
    paredeQuarto: Parede
    paredeCozinha: Parede
    paredeBanheiro: Parede
    EspelhoCorredor: Espelho
}

@enduml